### PR TITLE
Use configuration object, fixes #69

### LINKED ISSUE #69: Using multiple clients, before execute callbacks are shared between clients
Hello,

When using multiple clients I noticed that the before execute callbacks are shared between artemis instances, following script shows the problem

```ruby
require 'bundler/inline'

gemfile do
  gem 'artemis'
  gem 'awesome_print'
end

require 'artemis'
require 'ap'

class ClientA < Artemis::Client
  before_execute do |_, _, _, _|
    puts 'CLIENT A BEFORE EXECUTE'
  end
end

class ClientB < Artemis::Client
  before_execute do |_, _, _, _|
    puts 'CLIENT B BEFORE EXECUTE'
  end
end

ap ClientA.before_execute
```

I expect that `ClientA.before_execute` returns an Array of 2 element (where last element is nil) instead I get back an array of 3 procs. another slimmed down version that shows that in this case `ActiveSupport::Configurable` is not the solution you would want to use.

```ruby
class ConfigurableTest
  include ActiveSupport::Configurable

  config.before_callbacks = []

  class << self
    def before_execute(test)
      config.before_callbacks << test
    end
  end
end

class TestA < ConfigurableTest
  before_execute "a"
end

class TestB < ConfigurableTest
  before_execute "b"
end

ap TestA.config.before_callbacks
ap TestB.config.before_callbacks
ap ConfigurableTest.config.before_callbacks
```

I think it's best to move away from `ActiveSupport::Configurable` and just use regular class methods and variables

### PR DESCRIPTION
**Pull request by JanStevens**
Instead of using ActiveSupport::Configuration which will keep the config shared across inherited classes we now use a simple configuration object.

Not much needed to change, I've added an additional spec for the configuration

### CODE REVIEW

**Comment by JanStevens** [comment]
Hmm it seems that for `query_paths` the old configuration would still be needed, not sure if there is a general more better way to deal with this

**Comment by yuki24** [comment]
`ActiveSupport::Configuration` is actually already [inheritance-aware](https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/activesupport/lib/active_support/configurable.rb#L31-L36). What's happening here though, is that [the `#inheritable_copy` method doesn't deep-clone](https://api.rubyonrails.org/classes/ActiveSupport/InheritableOptions.html#method-i-inheritable_copy) and mutating any nested object would affect other configurations. We should probably just change these two lines:

https://github.com/yuki24/artemis/blob/daa66cc028cbf7f086d05056f8200f3ca803f51d/lib/artemis/client.rb#L140
https://github.com/yuki24/artemis/blob/daa66cc028cbf7f086d05056f8200f3ca803f51d/lib/artemis/client.rb#L158

to set a new value in a more functional way:

```diff
-config.before_callbacks << block
+config.before_callbacks = [*config.before_callbacks, block]

-config.after_callbacks << block
+config.after_callbacks = [*config.after_callbacks, block]
```

The `default_context` should probably be set to `nil` by default and it should fall back to an empty hash at runtime:

```ruby
config.default_context = nil

def default_context
  config.default_context || {}
end
```

e`config.query_paths` is a bit tricky. I would like it to be a gem-wide config and I like how it ends up being shared today. Though using `config` doesn't seem right, so maybe we should switch to a `cattr_reader`.

**Comment by yuki24** [comment]
Thanks!

**Comment by yuki24** [comment]
Fixes have been released as [`v0.5.1`](https://github.com/yuki24/artemis/releases/tag/v0.5.1).

**Pull request merged**
